//! The compiled kernel registry (generated by `build.rs`) and pipeline
//! creation. Callers deal in [`Kernel`]s; WGSL details (entry point names,
//! defines) never leak past this module.
//!
//! Descriptor-set layouts are built from the registry's `bindings` count, not
//! SPIR-V reflection: the kernels' coopmat operands are invisible to reflection
//! (the original reason this metadata is carried explicitly), and on `ash` we
//! drive `vkUpdateDescriptorSets` directly so we need the exact binding list.

use std::sync::Arc;

use ash::vk;

use crate::context::DeviceCtx;
use crate::{GpuContext, GpuError};

/// One build-time-compiled SPIR-V blob.
pub struct KernelBlob {
    pub name: &'static str,
    pub spv: &'static [u8],
    /// Workgroup size baked into the shader (single source of truth is the
    /// variant table in `build.rs`).
    pub workgroup: [u32; 3],
    /// Storage-buffer bindings at set 0, bindings `0..bindings`. The layout
    /// is built from this rather than SPIR-V reflection — reflection misses
    /// buffers consumed only by cooperative-matrix ops.
    pub bindings: u32,
    /// Push-constant byte size (0 = none).
    pub push_bytes: u32,
    /// Required subgroup size, 0 = driver default. The coopmat GEMM kernels
    /// pin 32: RDNA3 WMMA runs at half rate in wave64. (Currently every
    /// variant is 0; pinning a size also needs `subgroupSizeControl` enabled.)
    pub subgroup_size: u32,
}

include!(concat!(env!("OUT_DIR"), "/kernels.rs"));

/// Look up a compiled variant by name.
pub fn kernel_blob(name: &str) -> Option<&'static KernelBlob> {
    KERNELS.iter().find(|k| k.name == name)
}

/// A ready-to-bind compute pipeline and its layouts.
pub struct Kernel {
    pub name: &'static str,
    pub workgroup: [u32; 3],
    pub(crate) pipeline: vk::Pipeline,
    pub(crate) pipeline_layout: vk::PipelineLayout,
    pub(crate) set_layout: vk::DescriptorSetLayout,
    shader: vk::ShaderModule,
    ctx: Arc<DeviceCtx>,
}

impl Kernel {
    /// Workgroup count covering `n` invocations on the x axis.
    pub fn groups_for(&self, n: u64) -> [u32; 3] {
        [n.div_ceil(self.workgroup[0] as u64) as u32, 1, 1]
    }
}

impl Drop for Kernel {
    fn drop(&mut self) {
        // SAFETY: the kernel holds an Arc<DeviceCtx>, so the device outlives
        // this; no command buffer recorded against the pipeline is in flight
        // (graphs are dropped before the kernels they reference in practice,
        // and submits are fence-waited).
        unsafe {
            let d = &self.ctx.device;
            d.destroy_pipeline(self.pipeline, None);
            d.destroy_pipeline_layout(self.pipeline_layout, None);
            d.destroy_descriptor_set_layout(self.set_layout, None);
            d.destroy_shader_module(self.shader, None);
        }
    }
}

impl GpuContext {
    /// Build the pipeline for a registry kernel.
    pub fn load_kernel(&self, name: &str) -> Result<Kernel, GpuError> {
        let blob = kernel_blob(name).ok_or(GpuError::UnknownKernel(name.to_owned()))?;
        let device = self.device();

        // include_bytes! data is only 1-aligned; copy into u32 words.
        let words: Vec<u32> = blob
            .spv
            .chunks_exact(4)
            .map(|c| u32::from_le_bytes(c.try_into().expect("4-byte chunks")))
            .collect();
        let module_ci = vk::ShaderModuleCreateInfo::default().code(&words);
        // SAFETY: the words are naga-validated SPIR-V from our own build script.
        let shader = unsafe { device.create_shader_module(&module_ci, None) }
            .map_err(|e| GpuError::Pipeline(format!("create_shader_module {name}: {e}")))?;

        // Descriptor set layout: bindings 0..blob.bindings, all storage buffers.
        let bindings: Vec<vk::DescriptorSetLayoutBinding> = (0..blob.bindings)
            .map(|i| {
                vk::DescriptorSetLayoutBinding::default()
                    .binding(i)
                    .descriptor_type(vk::DescriptorType::STORAGE_BUFFER)
                    .descriptor_count(1)
                    .stage_flags(vk::ShaderStageFlags::COMPUTE)
            })
            .collect();
        let set_ci = vk::DescriptorSetLayoutCreateInfo::default().bindings(&bindings);
        // SAFETY: valid device; create info borrows live locals.
        let set_layout = unsafe { device.create_descriptor_set_layout(&set_ci, None) }
            .map_err(|e| {
                // SAFETY: clean up the shader on the failure path.
                unsafe { device.destroy_shader_module(shader, None) };
                GpuError::Pipeline(format!("create_descriptor_set_layout {name}: {e}"))
            })?;

        let set_layouts = [set_layout];
        let push_ranges = [vk::PushConstantRange::default()
            .stage_flags(vk::ShaderStageFlags::COMPUTE)
            .offset(0)
            .size(blob.push_bytes)];
        let mut layout_ci = vk::PipelineLayoutCreateInfo::default().set_layouts(&set_layouts);
        if blob.push_bytes > 0 {
            layout_ci = layout_ci.push_constant_ranges(&push_ranges);
        }
        // SAFETY: valid device; create info borrows live locals.
        let pipeline_layout = unsafe { device.create_pipeline_layout(&layout_ci, None) }
            .map_err(|e| {
                // SAFETY: clean up shader + set layout on the failure path.
                unsafe {
                    device.destroy_descriptor_set_layout(set_layout, None);
                    device.destroy_shader_module(shader, None);
                }
                GpuError::Pipeline(format!("create_pipeline_layout {name}: {e}"))
            })?;

        let stage = vk::PipelineShaderStageCreateInfo::default()
            .stage(vk::ShaderStageFlags::COMPUTE)
            .module(shader)
            .name(c"main");
        let pipeline_ci = vk::ComputePipelineCreateInfo::default()
            .stage(stage)
            .layout(pipeline_layout);
        // SAFETY: valid device; create info borrows live locals.
        let pipeline = unsafe {
            device.create_compute_pipelines(vk::PipelineCache::null(), &[pipeline_ci], None)
        }
        .map_err(|(_, e)| {
            // SAFETY: clean up all prior objects on the failure path.
            unsafe {
                device.destroy_pipeline_layout(pipeline_layout, None);
                device.destroy_descriptor_set_layout(set_layout, None);
                device.destroy_shader_module(shader, None);
            }
            GpuError::Pipeline(format!("create_compute_pipelines {name}: {e}"))
        })?[0];

        Ok(Kernel {
            name: blob.name,
            workgroup: blob.workgroup,
            pipeline,
            pipeline_layout,
            set_layout,
            shader,
            ctx: self.ctx.clone(),
        })
    }
}
