//! The compiled kernel registry (generated by `build.rs`) and pipeline
//! creation. Callers deal in [`Kernel`]s; WGSL details (entry point names,
//! defines) never leak past this module.

use std::collections::BTreeMap;
use std::sync::Arc;

use vulkano::descriptor_set::layout::{
    DescriptorSetLayout, DescriptorSetLayoutBinding, DescriptorSetLayoutCreateInfo, DescriptorType,
};
use vulkano::pipeline::compute::ComputePipelineCreateInfo;
use vulkano::pipeline::layout::{PipelineLayoutCreateInfo, PushConstantRange};
use vulkano::pipeline::{ComputePipeline, PipelineLayout, PipelineShaderStageCreateInfo};
use vulkano::shader::{ShaderModule, ShaderModuleCreateInfo, ShaderStages};

use crate::{GpuContext, GpuError};

/// One build-time-compiled SPIR-V blob.
pub struct KernelBlob {
    pub name: &'static str,
    pub spv: &'static [u8],
    /// Workgroup size baked into the shader (single source of truth is the
    /// variant table in `build.rs`).
    pub workgroup: [u32; 3],
    /// Storage-buffer bindings at set 0, bindings `0..bindings`. The layout
    /// is built from this rather than SPIR-V reflection — vulkano's
    /// reflection misses buffers consumed only by cooperative-matrix ops.
    pub bindings: u32,
    /// Push-constant byte size (0 = none).
    pub push_bytes: u32,
}

include!(concat!(env!("OUT_DIR"), "/kernels.rs"));

/// Look up a compiled variant by name.
pub fn kernel_blob(name: &str) -> Option<&'static KernelBlob> {
    KERNELS.iter().find(|k| k.name == name)
}

/// A ready-to-bind compute pipeline.
pub struct Kernel {
    pub name: &'static str,
    pub workgroup: [u32; 3],
    pipeline: Arc<ComputePipeline>,
}

impl Kernel {
    pub fn pipeline(&self) -> &Arc<ComputePipeline> {
        &self.pipeline
    }

    pub fn layout(&self) -> &Arc<PipelineLayout> {
        use vulkano::pipeline::Pipeline;
        self.pipeline.layout()
    }

    /// Workgroup count covering `n` invocations on the x axis.
    pub fn groups_for(&self, n: u64) -> [u32; 3] {
        [n.div_ceil(self.workgroup[0] as u64) as u32, 1, 1]
    }
}

impl GpuContext {
    /// Build the pipeline for a registry kernel.
    pub fn load_kernel(&self, name: &str) -> Result<Kernel, GpuError> {
        let blob = kernel_blob(name).ok_or(GpuError::UnknownKernel(name.to_owned()))?;
        // include_bytes! data is only 1-aligned; copy into u32 words.
        let words: Vec<u32> = blob
            .spv
            .chunks_exact(4)
            .map(|c| u32::from_le_bytes(c.try_into().expect("4-byte chunks")))
            .collect();
        // SAFETY: the words are naga-validated SPIR-V produced by our own
        // build script.
        let module = unsafe {
            ShaderModule::new(self.device().clone(), ShaderModuleCreateInfo::new(&words))
        }
        .map_err(GpuError::validated)?;
        let entry = module
            .entry_point("main")
            .ok_or(GpuError::UnknownKernel(format!(
                "{name}: no `main` entry point"
            )))?;
        let stage = PipelineShaderStageCreateInfo::new(entry);

        let set_layout = DescriptorSetLayout::new(
            self.device().clone(),
            DescriptorSetLayoutCreateInfo {
                bindings: (0..blob.bindings)
                    .map(|i| {
                        (
                            i,
                            DescriptorSetLayoutBinding {
                                stages: ShaderStages::COMPUTE,
                                ..DescriptorSetLayoutBinding::descriptor_type(
                                    DescriptorType::StorageBuffer,
                                )
                            },
                        )
                    })
                    .collect::<BTreeMap<_, _>>(),
                ..Default::default()
            },
        )
        .map_err(GpuError::validated)?;
        let layout = PipelineLayout::new(
            self.device().clone(),
            PipelineLayoutCreateInfo {
                set_layouts: vec![set_layout],
                push_constant_ranges: (blob.push_bytes > 0)
                    .then_some(PushConstantRange {
                        stages: ShaderStages::COMPUTE,
                        offset: 0,
                        size: blob.push_bytes,
                    })
                    .into_iter()
                    .collect(),
                ..Default::default()
            },
        )
        .map_err(GpuError::validated)?;
        let pipeline = ComputePipeline::new(
            self.device().clone(),
            None,
            ComputePipelineCreateInfo::stage_layout(stage, layout),
        )
        .map_err(GpuError::validated)?;

        Ok(Kernel {
            name: blob.name,
            workgroup: blob.workgroup,
            pipeline,
        })
    }
}
