//! Gemma 4 tokenizer built from the GGUF-embedded vocab, plus (M1, plan 01)
//! the chat/tool-call template and a streaming UTF-8-safe detokenizer.
//!
//! **Algorithm** (pinned 2026-06-11 from the official `tokenizer.json`, *not*
//! the SPM-unigram plan 01 originally assumed): BPE over 514 906 merges with
//! byte fallback, `" " → "▁"` normalization, no pre-tokenization, and 24
//! added special tokens matched leftmost-longest. Parity with HF `tokenizers`
//! is enforced by the golden corpus in `tests/fixtures/` (generated by
//! `tools/gen_tokenizer_fixtures.py`).

mod bpe;
mod detok;
mod tokenizer;
mod vocab;

pub use detok::DetokBuffer;
pub use tokenizer::{DecodeError, SpecialTokens, Tokenizer};
pub use vocab::{TokenType, Vocab, VocabError};
