//! Compiles every kernel variant from WGSL to SPIR-V at build time:
//! naga-oil composition (defines for per-shape specialization) -> naga
//! validation -> spv-out. The runtime never compiles shaders; a shader error
//! is a build error, catchable without a GPU.
//!
//! Output: one `<variant>.spv` per entry in `VARIANTS`, plus a generated
//! `kernels.rs` registry included by `src/kernel.rs`.

use std::collections::HashMap;
use std::fmt::Write as _;
use std::{env, fs, path::PathBuf};

use naga_oil::compose::ShaderDefValue;

/// One compiled pipeline: a WGSL source plus its specialization defines.
struct Variant {
    /// Registry/pipeline name; also the `.spv` file stem.
    name: &'static str,
    /// Source file under `shaders/`, without extension.
    src: &'static str,
    /// naga-oil shader defs (`#ifdef` / `#{NAME}` substitution).
    defs: &'static [(&'static str, u32)],
    /// Workgroup size, exported to the runtime for dispatch math. Sources
    /// reference it as `#{WG_X}` etc. so this table is the single source of
    /// truth.
    workgroup: [u32; 3],
}

const VARIANTS: &[Variant] = &[Variant {
    name: "stub",
    src: "stub",
    defs: &[],
    workgroup: [64, 1, 1],
}];

fn main() {
    println!("cargo::rerun-if-changed=shaders");
    let out_dir = PathBuf::from(env::var("OUT_DIR").unwrap());

    let mut registry = String::from(
        "/// Generated by build.rs — one entry per compiled kernel variant.\n\
         pub static KERNELS: &[KernelBlob] = &[\n",
    );
    for v in VARIANTS {
        let path = PathBuf::from(format!("shaders/{}.wgsl", v.src));
        let spv = compile(&path, v);
        let bytes: Vec<u8> = spv.iter().flat_map(|w| w.to_le_bytes()).collect();
        fs::write(out_dir.join(format!("{}.spv", v.name)), bytes).expect("write .spv");
        writeln!(
            registry,
            "    KernelBlob {{ name: {:?}, spv: include_bytes!(concat!(env!(\"OUT_DIR\"), \
             \"/{}.spv\")), workgroup: {:?} }},",
            v.name, v.name, v.workgroup
        )
        .unwrap();
    }
    registry.push_str("];\n");
    fs::write(out_dir.join("kernels.rs"), registry).expect("write kernels.rs");
}

fn compile(path: &std::path::Path, variant: &Variant) -> Vec<u32> {
    let source =
        fs::read_to_string(path).unwrap_or_else(|e| panic!("read {}: {e}", path.display()));
    let display = format!("{} [{}]", path.display(), variant.name);

    let mut shader_defs: HashMap<String, ShaderDefValue> = HashMap::new();
    shader_defs.insert("WG_X".into(), ShaderDefValue::UInt(variant.workgroup[0]));
    shader_defs.insert("WG_Y".into(), ShaderDefValue::UInt(variant.workgroup[1]));
    shader_defs.insert("WG_Z".into(), ShaderDefValue::UInt(variant.workgroup[2]));
    for (k, v) in variant.defs {
        shader_defs.insert((*k).to_owned(), ShaderDefValue::UInt(*v));
    }

    // The composer validates internally with its own capability set; default
    // capabilities reject immediates (push constants), f16, subgroups, …
    let mut composer =
        naga_oil::compose::Composer::default().with_capabilities(naga::valid::Capabilities::all());
    let module = composer
        .make_naga_module(naga_oil::compose::NagaModuleDescriptor {
            source: &source,
            file_path: &display,
            shader_defs,
            ..Default::default()
        })
        .unwrap_or_else(|e| panic!("compose {display}: {e}"));

    let info = naga::valid::Validator::new(
        naga::valid::ValidationFlags::all(),
        naga::valid::Capabilities::all(),
    )
    .validate(&module)
    .unwrap_or_else(|e| panic!("validate {display}: {e:?}"));

    naga::back::spv::write_vec(&module, &info, &naga::back::spv::Options::default(), None)
        .unwrap_or_else(|e| panic!("spv-out {display}: {e}"))
}
