//! Compiles every kernel variant from WGSL to SPIR-V at build time:
//! naga-oil composition (defines for per-shape specialization) -> naga
//! validation -> spv-out. The runtime never compiles shaders; a shader error
//! is a build error, catchable without a GPU.
//!
//! Output: one `<variant>.spv` per entry in `VARIANTS`, plus a generated
//! `kernels.rs` registry included by `src/kernel.rs`.

use std::collections::HashMap;
use std::fmt::Write as _;
use std::{env, fs, path::PathBuf};

use naga_oil::compose::ShaderDefValue;

/// One compiled pipeline: a WGSL source plus its specialization defines.
struct Variant {
    /// Registry/pipeline name; also the `.spv` file stem.
    name: &'static str,
    /// Source file under `shaders/`, without extension.
    src: &'static str,
    /// naga-oil shader defs (`#ifdef` / `#{NAME}` substitution).
    defs: &'static [(&'static str, u32)],
    /// Workgroup size, exported to the runtime for dispatch math. Sources
    /// reference it as `#{WG_X}` etc. so this table is the single source of
    /// truth.
    workgroup: [u32; 3],
}

/// Gemma 4 geometry (validated by `sg_gguf::ModelDesc` at load time): the
/// full set of shapes is known here, so every kernel is shape-specialized
/// (plan 02).
const VARIANTS: &[Variant] = &[
    Variant {
        name: "stub",
        src: "stub",
        defs: &[],
        workgroup: [64, 1, 1],
    },
    // RMSNorm: hidden rows + the two QK-norm head_dims, each in both weight
    // conventions (W_PLUS_ONE picked by M3 parity).
    Variant {
        name: "rmsnorm_5376",
        src: "rmsnorm",
        defs: &[("ROW_LEN", 5376)],
        workgroup: [256, 1, 1],
    },
    Variant {
        name: "rmsnorm_5376_plus1",
        src: "rmsnorm",
        defs: &[("ROW_LEN", 5376), ("W_PLUS_ONE", 1)],
        workgroup: [256, 1, 1],
    },
    Variant {
        name: "rmsnorm_512",
        src: "rmsnorm",
        defs: &[("ROW_LEN", 512)],
        workgroup: [256, 1, 1],
    },
    Variant {
        name: "rmsnorm_512_plus1",
        src: "rmsnorm",
        defs: &[("ROW_LEN", 512), ("W_PLUS_ONE", 1)],
        workgroup: [256, 1, 1],
    },
    Variant {
        name: "rmsnorm_256",
        src: "rmsnorm",
        defs: &[("ROW_LEN", 256)],
        workgroup: [256, 1, 1],
    },
    Variant {
        name: "rmsnorm_256_plus1",
        src: "rmsnorm",
        defs: &[("ROW_LEN", 256), ("W_PLUS_ONE", 1)],
        workgroup: [256, 1, 1],
    },
    // RoPE per attention site. Sliding: full rotation, θ=10k. Global:
    // partial rotation (0.25 × 512 = 128 dims), θ=1M.
    Variant {
        name: "rope_sliding_q",
        src: "rope",
        defs: &[("HEAD_DIM", 256), ("ROT_DIMS", 256), ("N_HEADS", 32)],
        workgroup: [256, 1, 1],
    },
    Variant {
        name: "rope_sliding_k",
        src: "rope",
        defs: &[("HEAD_DIM", 256), ("ROT_DIMS", 256), ("N_HEADS", 16)],
        workgroup: [256, 1, 1],
    },
    Variant {
        name: "rope_global_q",
        src: "rope",
        defs: &[("HEAD_DIM", 512), ("ROT_DIMS", 128), ("N_HEADS", 32)],
        workgroup: [256, 1, 1],
    },
    Variant {
        name: "rope_global_k",
        src: "rope",
        defs: &[("HEAD_DIM", 512), ("ROT_DIMS", 128), ("N_HEADS", 4)],
        workgroup: [256, 1, 1],
    },
    Variant {
        name: "geglu",
        src: "geglu",
        defs: &[],
        workgroup: [256, 1, 1],
    },
    // Q4_0 GEMV, one variant per matmul-site K (the N dimension is the
    // dispatch size). Workgroup = one wave (probe: subgroup 64).
    Variant {
        name: "gemv_q4_0_k5376",
        src: "gemv_q4_0",
        defs: &[("K_DIM", 5376)],
        workgroup: [64, 1, 1],
    },
    Variant {
        name: "gemv_q4_0_k8192",
        src: "gemv_q4_0",
        defs: &[("K_DIM", 8192)],
        workgroup: [64, 1, 1],
    },
    Variant {
        name: "gemv_q4_0_k16384",
        src: "gemv_q4_0",
        defs: &[("K_DIM", 16384)],
        workgroup: [64, 1, 1],
    },
    Variant {
        name: "gemv_q4_0_k21504",
        src: "gemv_q4_0",
        defs: &[("K_DIM", 21504)],
        workgroup: [64, 1, 1],
    },
    Variant {
        name: "gemv_q4_0_generic",
        src: "gemv_q4_0",
        defs: &[("GENERIC_K", 1)],
        workgroup: [64, 1, 1],
    },
];

fn main() {
    println!("cargo::rerun-if-changed=shaders");
    let out_dir = PathBuf::from(env::var("OUT_DIR").unwrap());

    let mut registry = String::from(
        "/// Generated by build.rs — one entry per compiled kernel variant.\n\
         pub static KERNELS: &[KernelBlob] = &[\n",
    );
    for v in VARIANTS {
        let path = PathBuf::from(format!("shaders/{}.wgsl", v.src));
        let spv = compile(&path, v);
        let bytes: Vec<u8> = spv.iter().flat_map(|w| w.to_le_bytes()).collect();
        fs::write(out_dir.join(format!("{}.spv", v.name)), bytes).expect("write .spv");
        writeln!(
            registry,
            "    KernelBlob {{ name: {:?}, spv: include_bytes!(concat!(env!(\"OUT_DIR\"), \
             \"/{}.spv\")), workgroup: {:?} }},",
            v.name, v.name, v.workgroup
        )
        .unwrap();
    }
    registry.push_str("];\n");
    fs::write(out_dir.join("kernels.rs"), registry).expect("write kernels.rs");
}

fn compile(path: &std::path::Path, variant: &Variant) -> Vec<u32> {
    let source =
        fs::read_to_string(path).unwrap_or_else(|e| panic!("read {}: {e}", path.display()));
    let display = format!("{} [{}]", path.display(), variant.name);

    let mut shader_defs: HashMap<String, ShaderDefValue> = HashMap::new();
    shader_defs.insert("WG_X".into(), ShaderDefValue::UInt(variant.workgroup[0]));
    shader_defs.insert("WG_Y".into(), ShaderDefValue::UInt(variant.workgroup[1]));
    shader_defs.insert("WG_Z".into(), ShaderDefValue::UInt(variant.workgroup[2]));
    for (k, v) in variant.defs {
        shader_defs.insert((*k).to_owned(), ShaderDefValue::UInt(*v));
    }

    // The composer validates internally with its own capability set; default
    // capabilities reject immediates (push constants), f16, subgroups, …
    let mut composer =
        naga_oil::compose::Composer::default().with_capabilities(naga::valid::Capabilities::all());
    let module = composer
        .make_naga_module(naga_oil::compose::NagaModuleDescriptor {
            source: &source,
            file_path: &display,
            shader_defs,
            ..Default::default()
        })
        .unwrap_or_else(|e| panic!("compose {display}: {e}"));

    let info = naga::valid::Validator::new(
        naga::valid::ValidationFlags::all(),
        naga::valid::Capabilities::all(),
    )
    .validate(&module)
    .unwrap_or_else(|e| panic!("validate {display}: {e:?}"));

    // Whitelist the SPIR-V capabilities matching the device features
    // GpuContext enables; without this naga reaches for capabilities like
    // StorageInputOutput16 (16-bit stage IO) that compute storage access
    // doesn't need and the device doesn't enable. Needing a capability
    // outside this set is a build error — extend both this list and
    // `context::required_features` together.
    let capabilities = [
        naga::back::spv::Capability::Shader,
        naga::back::spv::Capability::Float16,
        naga::back::spv::Capability::Int8,
        naga::back::spv::Capability::Int16,
        naga::back::spv::Capability::StorageBuffer16BitAccess,
        naga::back::spv::Capability::UniformAndStorageBuffer16BitAccess,
        naga::back::spv::Capability::GroupNonUniform,
        naga::back::spv::Capability::GroupNonUniformArithmetic,
        naga::back::spv::Capability::GroupNonUniformBallot,
        naga::back::spv::Capability::GroupNonUniformShuffle,
        naga::back::spv::Capability::GroupNonUniformShuffleRelative,
        naga::back::spv::Capability::CooperativeMatrixKHR,
        naga::back::spv::Capability::VulkanMemoryModel,
    ];
    let options = naga::back::spv::Options {
        capabilities: Some(capabilities.into_iter().collect()),
        // No f16 stage IO in compute; without this naga declares
        // StorageInputOutput16 whenever f16 is enabled.
        use_storage_input_output_16: false,
        ..Default::default()
    };
    naga::back::spv::write_vec(&module, &info, &options, None)
        .unwrap_or_else(|e| panic!("spv-out {display}: {e}"))
}
