//! CPU reference vs llama.cpp on the SAME GGUF (plan 06 rung 4, pulled
//! forward to M3 to confirm the pinned forward-graph reading).
//!
//! Fixtures: `tests/fixtures/llamacpp_logits.jsonl`, generated by
//! `tools/gen_logits_fixtures.py` from the installed llama.cpp's **CPU
//! backend** (f32 accumulation — the tightest available oracle for our
//! f32/f64 reference; version in the header line). Comparison is
//! tolerance-based, not equality (plan 06).
//!
//! Threshold calibration (2026-06-12, measured): at 2054 tokens llama.cpp
//! disagrees with ITSELF — HIP flash-attention vs HIP no-fa vs CPU backend
//! span Δ 0.41 logprob on top-20 tokens, top-20 KL 0.030 between its own
//! two GPU modes. So: short prompts assert argmax, overlap ≥ 15/20,
//! KL ≤ 0.005, and |Δ| ≤ 0.15 (logprob > −5); the long prompt asserts
//! argmax, overlap, and KL ≤ 0.05, dropping the per-token Δ check, which
//! cannot be tighter than the reference's own backend spread there.
//! Tighten with suite history; loosening needs a justified plan change.
//!
//! Every metric is evaluated and printed before any assert: a long-prompt
//! oracle run costs minutes — one run must yield complete data.

use std::path::PathBuf;

use sg_model::{CpuKvCache, CpuModel};

fn model_path() -> Option<PathBuf> {
    if let Ok(p) = std::env::var("SG_MODEL_GGUF") {
        return Some(p.into());
    }
    let p = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../../models/gemma-4-31B_q4_0-it.gguf");
    p.exists().then_some(p)
}

struct Fixture {
    name: String,
    ids: Vec<u32>,
    /// (token id, logprob), descending.
    top: Vec<(u32, f64)>,
}

struct Thresholds {
    min_overlap: usize,
    max_kl: f64,
    /// `None` disables the per-token check (long contexts: the reference's
    /// own backend spread exceeds any useful bound).
    max_logprob_delta: Option<f64>,
}

impl Thresholds {
    fn for_len(n_tokens: usize) -> Self {
        if n_tokens <= 256 {
            Self {
                min_overlap: 15,
                max_kl: 0.005,
                max_logprob_delta: Some(0.15),
            }
        } else {
            Self {
                min_overlap: 15,
                max_kl: 0.05,
                max_logprob_delta: None,
            }
        }
    }
}

fn load_fixtures() -> Vec<Fixture> {
    let path =
        PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("tests/fixtures/llamacpp_logits.jsonl");
    let text = std::fs::read_to_string(path).expect("fixture file (tools/gen_logits_fixtures.py)");
    text.lines()
        .skip(1) // generator header
        .map(|line| {
            let v: serde_json::Value = serde_json::from_str(line).expect("fixture line");
            Fixture {
                name: v["name"].as_str().unwrap().to_owned(),
                ids: v["ids"]
                    .as_array()
                    .unwrap()
                    .iter()
                    .map(|t| t.as_u64().unwrap() as u32)
                    .collect(),
                top: v["top_logprobs"]
                    .as_array()
                    .unwrap()
                    .iter()
                    .map(|t| {
                        (
                            t["id"].as_u64().unwrap() as u32,
                            t["logprob"].as_f64().unwrap(),
                        )
                    })
                    .collect(),
            }
        })
        .collect()
}

/// Full-vocab log-softmax in f64.
fn log_softmax(logits: &[f32]) -> Vec<f64> {
    let max = logits.iter().cloned().fold(f32::NEG_INFINITY, f32::max) as f64;
    let lse: f64 = logits
        .iter()
        .map(|&v| (v as f64 - max).exp())
        .sum::<f64>()
        .ln()
        + max;
    logits.iter().map(|&v| v as f64 - lse).collect()
}

/// Evaluate ALL metrics, print them, and return the violations (empty =
/// pass). Asserting happens in the caller after every fixture has run.
fn check_parity(fix: &Fixture, model: &CpuModel<'_>) -> Vec<String> {
    let thr = Thresholds::for_len(fix.ids.len());
    let mut cache = CpuKvCache::new(&model.desc);
    let logits = model.forward(&fix.ids, &mut cache, &mut |_, _, _| {});
    let vocab = model.desc.vocab_size;
    let lp = log_softmax(&logits);

    let mut idx: Vec<u32> = (0..vocab as u32).collect();
    idx.sort_unstable_by(|&a, &b| lp[b as usize].total_cmp(&lp[a as usize]));
    let ours_top: Vec<u32> = idx[..fix.top.len()].to_vec();

    let mut violations = Vec::new();

    if ours_top[0] != fix.top[0].0 {
        violations.push(format!(
            "{}: argmax mismatch (ours {} lp {:.4}, llama.cpp {} lp {:.4})",
            fix.name, ours_top[0], lp[ours_top[0] as usize], fix.top[0].0, fix.top[0].1
        ));
    }

    let overlap = fix
        .top
        .iter()
        .filter(|(id, _)| ours_top.contains(id))
        .count();
    if overlap < thr.min_overlap {
        violations.push(format!(
            "{}: top-20 rank overlap {overlap}/20 < {}",
            fix.name, thr.min_overlap
        ));
    }

    let mut max_delta: (f64, u32) = (0.0, 0);
    for &(id, theirs) in fix.top.iter().filter(|(_, l)| *l > -5.0) {
        let delta = (lp[id as usize] - theirs).abs();
        if delta > max_delta.0 {
            max_delta = (delta, id);
        }
        if let Some(bound) = thr.max_logprob_delta
            && delta > bound
        {
            violations.push(format!(
                "{}: token {id} logprob ours {:.4} vs llama.cpp {theirs:.4} (Δ {delta:.4} > {bound})",
                fix.name, lp[id as usize]
            ));
        }
    }

    // KL over llama.cpp's top-20 support, both sides renormalized.
    let q_mass: f64 = fix.top.iter().map(|(_, l)| l.exp()).sum();
    let p_mass: f64 = fix.top.iter().map(|(id, _)| lp[*id as usize].exp()).sum();
    let kl: f64 = fix
        .top
        .iter()
        .map(|(id, l)| {
            let q = l.exp() / q_mass;
            let p = lp[*id as usize].exp() / p_mass;
            q * (q / p).ln()
        })
        .sum();
    if kl > thr.max_kl {
        violations.push(format!("{}: top-20 KL {kl:.5} > {}", fix.name, thr.max_kl));
    }

    eprintln!(
        "{} ({} tokens): argmax {}, overlap {overlap}/20, KL {kl:.5}, \
         max Δ {:.4} @ id {} — {}",
        fix.name,
        fix.ids.len(),
        if ours_top[0] == fix.top[0].0 {
            "ok"
        } else {
            "MISMATCH"
        },
        max_delta.0,
        max_delta.1,
        if violations.is_empty() {
            "pass"
        } else {
            "FAIL"
        }
    );
    violations
}

fn run(filter: impl Fn(&Fixture) -> bool) {
    let Some(path) = model_path() else {
        eprintln!("skipping: model GGUF not present (set SG_MODEL_GGUF)");
        return;
    };
    let file = sg_gguf::GgufFile::open(&path).expect("open model");
    let gguf = file.parse().expect("parse model");
    let model = CpuModel::new(&gguf).expect("reference model");
    let mut violations = Vec::new();
    for fix in load_fixtures().iter().filter(|f| filter(f)) {
        violations.extend(check_parity(fix, &model));
    }
    assert!(violations.is_empty(), "{}", violations.join("\n"));
}

#[test]
fn short_prompts_match_llamacpp() {
    run(|f| f.ids.len() <= 256);
}

/// The >1024-token prompt crosses the sliding window — the case that
/// validates window masking + large-position rope against an independent
/// implementation. Minutes through the CPU oracle, so nightly / explicit:
/// `cargo nextest run -p sg-model --run-ignored all -E 'test(long_window)'`.
#[test]
#[ignore = "expensive: ~2K-token prefill through the CPU oracle"]
fn long_window_prompt_matches_llamacpp() {
    run(|f| f.ids.len() > 256);
}
