//! CPU reference vs llama.cpp on the SAME GGUF (plan 06 rung 4, pulled
//! forward to M3 to confirm the pinned forward-graph reading).
//!
//! Fixtures: `tests/fixtures/llamacpp_logits.jsonl`, generated by
//! `tools/gen_logits_fixtures.py` from the installed llama.cpp (version in
//! the header line). Comparison is tolerance-based — llama.cpp runs f16 GPU
//! kernels, we run f32/f64 — so rank overlap + top-20 KL, not equality
//! (plan 06 explains why same-file llama.cpp isolates our numerics from
//! quantization effects).
//!
//! Thresholds are initial calibrations (2026-06-12): argmax equal, ≥ 15/20
//! rank overlap, KL(top-20, renormalized) ≤ 0.02, |Δlogprob| ≤ 0.15 for
//! fixture tokens with logprob > −5 (below that, llama.cpp's f16 kernel
//! noise dominates the log-space delta — observed Δ 0.19 at p ≈ 2e-4 on a
//! peaked distribution while KL was fine). Tighten after the suite has
//! history; loosening needs a justified plan change.

use std::path::PathBuf;

use sg_model::{CpuKvCache, CpuModel};

fn model_path() -> Option<PathBuf> {
    if let Ok(p) = std::env::var("SG_MODEL_GGUF") {
        return Some(p.into());
    }
    let p = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../../models/gemma-4-31B_q4_0-it.gguf");
    p.exists().then_some(p)
}

struct Fixture {
    name: String,
    ids: Vec<u32>,
    /// (token id, logprob), descending.
    top: Vec<(u32, f64)>,
}

fn load_fixtures() -> Vec<Fixture> {
    let path =
        PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("tests/fixtures/llamacpp_logits.jsonl");
    let text = std::fs::read_to_string(path).expect("fixture file (tools/gen_logits_fixtures.py)");
    text.lines()
        .skip(1) // generator header
        .map(|line| {
            let v: serde_json::Value = serde_json::from_str(line).expect("fixture line");
            Fixture {
                name: v["name"].as_str().unwrap().to_owned(),
                ids: v["ids"]
                    .as_array()
                    .unwrap()
                    .iter()
                    .map(|t| t.as_u64().unwrap() as u32)
                    .collect(),
                top: v["top_logprobs"]
                    .as_array()
                    .unwrap()
                    .iter()
                    .map(|t| {
                        (
                            t["id"].as_u64().unwrap() as u32,
                            t["logprob"].as_f64().unwrap(),
                        )
                    })
                    .collect(),
            }
        })
        .collect()
}

/// Full-vocab log-softmax in f64.
fn log_softmax(logits: &[f32]) -> Vec<f64> {
    let max = logits.iter().cloned().fold(f32::NEG_INFINITY, f32::max) as f64;
    let lse: f64 = logits
        .iter()
        .map(|&v| (v as f64 - max).exp())
        .sum::<f64>()
        .ln()
        + max;
    logits.iter().map(|&v| v as f64 - lse).collect()
}

fn check_parity(fix: &Fixture, model: &CpuModel<'_>) {
    let mut cache = CpuKvCache::new(&model.desc);
    let logits = model.forward(&fix.ids, &mut cache, &mut |_, _, _| {});
    let vocab = model.desc.vocab_size;
    let last = &logits[(fix.ids.len() - 1) * vocab..];
    let lp = log_softmax(last);

    // Our top-20 by logprob.
    let mut idx: Vec<u32> = (0..vocab as u32).collect();
    idx.sort_unstable_by(|&a, &b| lp[b as usize].total_cmp(&lp[a as usize]));
    let ours_top: Vec<u32> = idx[..fix.top.len()].to_vec();

    assert_eq!(
        ours_top[0], fix.top[0].0,
        "{}: argmax mismatch (ours {} lp {:.4}, llama.cpp {} lp {:.4})",
        fix.name, ours_top[0], lp[ours_top[0] as usize], fix.top[0].0, fix.top[0].1
    );

    let overlap = fix
        .top
        .iter()
        .filter(|(id, _)| ours_top.contains(id))
        .count();
    assert!(
        overlap >= 15,
        "{}: top-20 rank overlap {overlap}/20 < 15",
        fix.name
    );

    for &(id, theirs) in fix.top.iter().filter(|(_, l)| *l > -5.0) {
        let delta = (lp[id as usize] - theirs).abs();
        assert!(
            delta <= 0.15,
            "{}: token {id} logprob ours {:.4} vs llama.cpp {:.4} (Δ {delta:.4})",
            fix.name,
            lp[id as usize],
            theirs
        );
    }

    // KL over llama.cpp's top-20 support, both sides renormalized.
    let q_mass: f64 = fix.top.iter().map(|(_, l)| l.exp()).sum();
    let p_mass: f64 = fix.top.iter().map(|(id, _)| lp[*id as usize].exp()).sum();
    let kl: f64 = fix
        .top
        .iter()
        .map(|(id, l)| {
            let q = l.exp() / q_mass;
            let p = lp[*id as usize].exp() / p_mass;
            q * (q / p).ln()
        })
        .sum();
    assert!(kl <= 0.02, "{}: top-20 KL {kl:.5} > 0.02", fix.name);
    eprintln!("{}: overlap {overlap}/20, KL {kl:.5} — ok", fix.name);
}

#[test]
fn short_prompts_match_llamacpp() {
    let Some(path) = model_path() else {
        eprintln!("skipping: model GGUF not present (set SG_MODEL_GGUF)");
        return;
    };
    let file = sg_gguf::GgufFile::open(&path).expect("open model");
    let gguf = file.parse().expect("parse model");
    let model = CpuModel::new(&gguf).expect("reference model");
    for fix in load_fixtures().iter().filter(|f| f.ids.len() <= 256) {
        check_parity(fix, &model);
    }
}

/// The >1024-token prompt crosses the sliding window; the CPU oracle needs
/// tens of minutes of scalar matmuls for it. Nightly / explicit runs only:
/// `cargo nextest run -p sg-model --run-ignored all -E 'test(long_window)'`.
#[test]
#[ignore = "expensive: ~2K-token prefill through the scalar CPU oracle"]
fn long_window_prompt_matches_llamacpp() {
    let Some(path) = model_path() else {
        eprintln!("skipping: model GGUF not present (set SG_MODEL_GGUF)");
        return;
    };
    let file = sg_gguf::GgufFile::open(&path).expect("open model");
    let gguf = file.parse().expect("parse model");
    let model = CpuModel::new(&gguf).expect("reference model");
    for fix in load_fixtures().iter().filter(|f| f.ids.len() > 256) {
        check_parity(fix, &model);
    }
}
